//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Automation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SiparisDetay
    {
        public int SiparisDetayi_Id { get; set; }
        public int SiparisId { get; set; }
        public int Urun_Id { get; set; }
        public decimal BirimFiyat { get; set; }
        public decimal Miktar { get; set; }
        public decimal Indirim { get; set; }
        public decimal Toplam { get; set; }
    
        public virtual Siparisler Siparisler { get; set; }
    }
}
