//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Automation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Urunler
    {
        public int Urun_Id { get; set; }
        public string Urun_Ismi { get; set; }
        public decimal Urun_Fiyat { get; set; }
    }
}
